#!/bin/sh

name=itpkg

case $1 in
	build)
		read -p "Do you wish to rebuild all steps?(y/n)" yn
		case $yn in
			y)
				ARGS=--no-cache
				;;
			*)
				ARGS=
				;;
		esac

		docker build $ARGS -t chonglou/itpkg .
		;;
	push)
		docker push chonglou/itpkg
		;;
	pull)
		docker pull chonglou/itpkg
		;;
	run)
		docker run -d --name itpkg -p 2222:22 -p 443:443 -P --privileged -v /sys/fs/cgroup:/sys/fs/cgroup:ro chonglou/itpkg:latest 		
		;;
	start)
		docker start itpkg
		;;
	stop)
		docker stop itpkg
		docker rm itpkg
		sed -i '/^\[localhost\]\:2222/ d' ~/.ssh/known_hosts
		;;
	ssh)
		ssh -p 2222 root@localhost
		;;
	info)
		docker version
		docker info
		;;
	clean)
		docker rm $(docker ps -a -q)
		docker rmi $(docker images -q --filter "dangling=true")
		;;
	*)
		echo "Usage: ./dh (info|build|run|start|stop|commit|push|pull)"
esac
