#!/bin/sh

case $1 in
	build)
		read -p "Do you wish to rebuild all steps?(y/n)" yn
		case $yn in
			y)
				ARGS=--no-cache
				;;
			*)
				ARGS=
				;;
		esac

		docker build $ARGS -t chonglou/$2 .
		;;
	commit)
		docker commit -m="$2" $1 chonglou/$1:latest
		;;
	push)
		docker push chonglou/$2
		;;
	pull)
		docker pull chonglou/$2
		;;
	run)
		docker run -d --name $2 -p 2222:22 -p 8080:8080 -p 443:443 -P --privileged -v /sys/fs/cgroup:/sys/fs/cgroup:ro chonglou/$2:latest 		
		;;
	start)
		docker start $2
		;;
	stop)
		docker stop $2
		docker rm $2
		sed -i '/^\[localhost\]\:2222/ d' ~/.ssh/known_hosts
		;;
	ssh)
		ssh -p 2222 root@localhost
		;;
	info)
		docker version
		docker info
		;;
	clean)
		docker rm $(docker ps -a -q)
		docker rmi $(docker images -q --filter "dangling=true")
		;;
	*)
		echo "Usage: ./dh (info|build|run|start|stop|commit|push|pull) NAME"
esac
