#!/bin/sh

if [ ! -d $2 ]
then
	echo "$2 not exists!"
	exit -1
fi

case $1 in
	build)
		read -p "Do you wish to rebuild all steps?(y/n)" yn
		case $yn in
			y)
				ARGS=--no-cache
				;;
			*)
				ARGS=
				;;
		esac

		docker build $ARGS -t chonglou/$2 $2
		;;
	commit)
		docker commit -m="$2" $1 chonglou/$1:latest
		;;
	push)
		docker push chonglou/$1
		;;
	start)
		docker run -d --name $2 -p 2222:22 -P --privileged -v /sys/fs/cgroup:/sys/fs/cgroup:ro chonglou/$2:latest 		
		;;
	stop)
		docker stop $2
		docker rm $2
		sed -i '/^\[localhost\]\:2222/ d' ~/.ssh/known_hosts
		;;
	ssh)
		ssh -p 2222 root@localhost
		;;
	info)
		docker version
		docker info
		;;
	clean)
		docker rm $(docker ps -a -q)
		docker rmi $(docker images -q --filter "dangling=true")
		;;
	*)
		echo "Usage: run.sh (info|build|stop|commit|push|start) NAME"
esac
